import requests

def search_real_jobs(query, location="", num_results=3):
    """
    Fetch real jobs from Arbeitnow API (FREE, no API key needed)
    """
    print(">>> Calling search_real_jobs with query:", query)

    url = "https://www.arbeitnow.com/api/job-board-api"

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        jobs = []
        job_data = data.get("data", [])

        # Filter jobs by query keywords
        query_lower = query.lower()
        filtered_jobs = [
            job for job in job_data
            if query_lower in job.get("title", "").lower()
            or query_lower in job.get("description", "").lower()
            or any(tag.lower() in query_lower for tag in job.get("tags", []))
        ]

        # If no matches, just take first few jobs
        if not filtered_jobs:
            filtered_jobs = job_data[:num_results]

        for job in filtered_jobs[:num_results]:
            jobs.append({
                "role": job.get("title", "N/A"),
                "company": job.get("company_name", "N/A"),
                "location": job.get("location", "Remote"),
                "salary_range": "Not specified",
                "deadline": "Rolling",
                "fit_score": 0,     # Will be calculated by AI
                "reasoning": "",    # Will be generated by AI
                "apply_link": job.get("url", "#"),
                "description": job.get("description", "")[:500],
                "tags": ", ".join(job.get("tags", [])),
            })

        print(">>> Real jobs fetched:", len(jobs))
        return jobs

    except Exception as e:
        print(f"Error fetching jobs from Arbeitnow: {e}")
        return []